version: "2"

volumes:
  data:
  logs:

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${PWD}/mosquitto.config:/mosquitto/config/mosquitto.conf
      - data:/mosquitto/data
      - logs:/mosquitto/logs
  bridge:
    build: ../mqtt-sns-bridge
    extra_hosts:
      localstack: 192.168.1.3
